{
 "title": "Alerting Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Server Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{ mode!=\"idle\"}[5m])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{}[5m])))) * 100",
       "legendFormat": "Instance - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(100 - ((node_filesystem_avail_bytes{device!~'rootfs'} * 100) / node_filesystem_size_bytes{device!~'rootfs'})) by (instance, mountpoint)",
       "legendFormat": "{{instance}}-{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{job=\"node-exporter\"}/1024/1024/1024",
       "legendFormat": "Node-{{instance}}"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(node_load5 / count by (instance, job) (node_cpu_seconds_total{mode=\"idle\"})) * 100",
       "legendFormat": "Instance - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\"}[1m])*8",
       "legendFormat": "Incoming - {{instance}}-{{device}}-{{job}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\"}[1m])*8",
       "legendFormat": "Outgoing - {{instance}}-{{device}}-{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Cluster Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Pod Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"k8s-master-194-163-133-199\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-133-199\",resource=\"pods\"})*100",
       "legendFormat": "Pod Capacity-k8s-master-194-163-133-199"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"k8s-master-194-163-135-72\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-135-72\",resource=\"pods\"})*100",
       "legendFormat": "Pod Capacity-k8s-master-194-163-135-72"
      }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"k8s-master-194-163-135-72\",resource=\"cpu\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-135-72\",resource=\"cpu\"})*100",
       "legendFormat": "CPU Capacity: k8s-master-194-163-135-72"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"k8s-master-194-163-133-199\",resource=\"cpu\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-133-199\",resource=\"cpu\"})*100",
       "legendFormat": "CPU Capacity: k8s-master-194-163-133-199"
      }
     ]
    },
    {
     "title": "Cluster Memory Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"k8s-master-194-163-133-199\",resource=\"memory\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-133-199\",resource=\"memory\"})*100",
       "legendFormat": "Memory Capacity - k8s-master-194-163-133-199"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"k8s-master-194-163-135-72\",resource=\"memory\"})/sum(kube_node_status_allocatable{node=~\"k8s-master-194-163-135-72\",resource=\"memory\"})*100",
       "legendFormat": "Memory Capacity - k8s-master-194-163-135-72"
      }
     ]
    },
    {
     "title": "Deployment Replicaset Unavailability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{})",
       "legendFormat": "Replica Count"
      }
     ]
    },
    {
     "title": "Node Availability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(up{job=\"node-exporter\"})",
       "legendFormat": "Node Count"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{}[30m])>1",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Failed Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Pending|Unknown\"})",
       "legendFormat": "Failed Pods"
      }
     ]
    },
    {
     "title": "Failed Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(kube_job_status_failed{})", "legendFormat": "Failed Jobs" }
     ]
    },
    {
     "title": "Statefulset Availability ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{}/kube_statefulset_status_replicas{}*100",
       "legendFormat": "Statefulset - {{statefulset}}"
      }
     ]
    },
    {
     "title": "Unbound PVC Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    }
   ]
  },
  { "title": "Application Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "API Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum( eas_http_response_time_sum ) by (x,service, nodeID) - sum ( eas_http_response_time_sum offset 5m ) by (x,service, nodeID)) / \r\n(sum( eas_http_response_time_count ) by (x,service, nodeID) - sum ( eas_http_response_time_count offset 5m ) by (x,service, nodeID))",
     "legendFormat": "{{service}}:{{nodeID}}"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(eas_http_request_total) by (x) - sum (eas_http_request_total offset 5m ) by (x)) / 5",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eas_http_request_error_total",
     "legendFormat": "{{service}}-{{nodeId}}-{{status}}"
    }
   ]
  }
 ]
}