{
 "title": "Stats Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Rate - 50th Percentile",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(eas_http_response_time_bucket[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Response Rate - 75th Percentile",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.65, sum(rate(eas_http_response_time_bucket[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Response Rate - 95th Percentile",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(eas_http_response_time_bucket[$__interval])) by (le))"
    }
   ]
  },
  {
   "title": "Avg Response Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(eas_http_response_time_sum{nodeID!~\"eas-internal-api-.*\"}) by (x,service, nodeID) - sum (eas_http_response_time_sum{nodeID!~\"eas-internal-api-.*\"} offset $__interval) by (x,service, nodeID)) / \r\n(sum(eas_http_response_time_count{nodeID!~\"eas-internal-api-.*\"}) by (x,service, nodeID) - sum (eas_http_response_time_count{nodeID!~\"eas-internal-api-.*\"} offset $__interval) by (x,service, nodeID))",
     "legendFormat": "{{service}}-{{nodeID}}"
    }
   ]
  },
  {
   "title": "HS6P Request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum( eas_hs6p_response_time_sum ) by (x,service, nodeID) - sum ( eas_hs6p_response_time_sum offset $__interval ) by (x,service, nodeID)) / \r\n(sum( eas_hs6p_response_time_count ) by (x,service, nodeID) - sum ( eas_hs6p_response_time_count offset $__interval ) by (x,service, nodeID))",
     "legendFormat": "{{nodeID}}"
    }
   ]
  }
 ]
}